security:
  basic:
    enabled: true
spring:
  application:
    name: microservice-discovery-eureka-ha
  security:
    user:
      name: "admin"
      password: "admin123"
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka,http://admin:admin123@localhost:8762/eureka

---
spring:
  profiles: peer1               #use to determine which profiles will be active
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
#  client:
#    #registerWithEureka: false   #mean whether register self to Eureka Server, default true, but this server is Eureka Server so set it false
#    #fetchRegistry: false        #mean whether need get the register info from Eureka Server, default true, but this is one-node Eureka Server, don't need to get register from other Eureka Server so set it false
#    service-url:
#      defaultZone: http://peer2:8762/eureka   #set the url for Eureka Server, search and register to Eureka Server through this url. Can be multi, use ',' to split.

---
spring:
  profiles: peer2                 #use to determine which profiles will be active
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
#  client:
#    #registerWithEureka: false   #mean whether register self to Eureka Server, default true, but this server is Eureka Server so set it false
#    #fetchRegistry: false        #mean whether need get the register info from Eureka Server, default true, but this is one-node Eureka Server, don't need to get register from other Eureka Server so set it false
#    service-url:
#      defaultZone: http://peer1:8761/eureka   #set the url for Eureka Server, search and register to Eureka Server through this url. Can be multi, use ',' to split.
